### ISSUE TITLE
ImportError: No module named 'faster_rcnn.nms._ext.nms._nms'

### ISSUE THREAD

**Issue by wangken1994** [Jacqueline121/Faster_RCNN_pytorch#1]
Hi, @Jacqueline121 
I met some errors when I ran your codes. The errors were shown below:
```
Traceback (most recent call last):
  File ".../Faster_RCNN_pytorch-master/train.py", line 12, in <module>
    from faster_rcnn.faster_rcnn import FasterRCNN
  File ".../Faster_RCNN_pytorch-master/faster_rcnn/faster_rcnn.py", line 7, in <module>
    from .rpn.rpn import RPN
  File ".../Faster_RCNN_pytorch-master/faster_rcnn/rpn/rpn.py", line 6, in <module>
    from .proposal import proposal
  File ".../Faster_RCNN_pytorch-master/faster_rcnn/rpn/proposal.py", line 6, in <module>
    from ..nms.nms_wrapper import nms
  File ".../Faster_RCNN_pytorch-master/faster_rcnn/nms/nms_wrapper.py", line 10, in <module>
    from .nms_gpu import nms_gpu
  File ".../Faster_RCNN_pytorch-master/faster_rcnn/nms/nms_gpu.py", line 3, in <module>
    from ._ext import nms
  File ".../Faster_RCNN_pytorch-master/faster_rcnn/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: No module named 'faster_rcnn.nms._ext.nms._nms'
```
So could you give me some tips?

**Comment by wangken1994** [comment]
First we should do `sh make.sh`. And there lack of `nms_cuda.c` in the path `.../faster_rcnn/nms/src/`. I got this file from [https://github.com/tztztztztz/faster-rcnn.pytorch](url), thanks to her!

[nms_cuda.c.zip](https://github.com/Jacqueline121/Faster_RCNN_pytorch/files/3359163/nms_cuda.c.zip)

**Comment by CC012118** [comment]
Thank you! It's my fault that I didn't notice the .gitignore file. So nms_cuda.c  file wasn't submitted to this repository. And I have changed the .gitignore file and committed the nms_cuda.c file.
