### ISSUE TITLE
Error caused by pytoch version

### ISSUE THREAD

**Issue by volmodaoist** [Jacqueline121/Faster_RCNN_pytorch#4]
The following code in `build. py` led to an error：torch.utils.ffi is deprecated. Please use cpp extensions instead.
```Python
from torch.utils.ffi import create_extension
```
After I replace `from torch.utils.ffi import create_extension`  to `from torch.utils.cpp_extension import BuildExtension` and  ` create_extension`  to `BuildExtension` , the new bugs appear…

```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda/'
/mnt/e/Mycode/FastRCNN/Faster_RCNN_pytorch/faster_rcnn/nms
['/mnt/e/Mycode/FastRCNN/Faster_RCNN_pytorch/faster_rcnn/nms/src/nms_cuda_kernel.cu.o']
Traceback (most recent call last):
  File "build.py", line 30, in <module>
    ffi = BuildExtension(
  File "/root/dlenv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 372, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/root/dlenv/lib/python3.8/site-packages/setuptools/__init__.py", line 178, in __init__      
    _Command.__init__(self, dist)
  File "/usr/lib/python3.8/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
Compiling roi pooling kernels by nvcc...
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda/'
/mnt/e/Mycode/FastRCNN/Faster_RCNN_pytorch/faster_rcnn/roi_pooling
Traceback (most recent call last):
  File "build.py", line 33, in <module>
    ffi = BuildExtension(
  File "/root/dlenv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 372, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/root/dlenv/lib/python3.8/site-packages/setuptools/__init__.py", line 178, in __init__      
    _Command.__init__(self, dist)
  File "/usr/lib/python3.8/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
```

**Comment by volmodaoist** [comment]
代码pytorch版本似乎是用0.4.0写就的，有没有什么不降级pytorch版本的方法让代码跑起来…我搜索几篇博客说只要替换几句代码，但是我替换之后仍然会有很迷的报错…
